version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nasondas-frontend
    restart: unless-stopped
    networks:
    - proxy

networks:
    proxy:
        external: true
